--- #<<iptables configuration>>
- hosts: all 
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
   - name:  firewalld
     yum:
       name: firewalld
       state: installed
   - name: enabling firewalld
     service:
       name: firewalld
       enabled: yes
   - name: starting firewalld
     service:
       name: firewalld
       state: started 
   - name: Installing iptables service
     yum: 
      name: iptables-services
      state: latest
   - name: Enabling iptables service
     service:
       name: iptables
       enabled: yes
   - name: Starting iptables
     service:
       name: iptables
       state: started
   - name: starting firewalld
     service:
       name: firewalld
       state: restarted
   - name: IPtable configuration
     become: yes
     shell: iptables -A INPUT -p tcp -s '{{item}}' -m multiport --dports 7000,9042 -m state --state NEW,ESTABLISHED -j ACCEPT
     with_items:
        - 10.1.53.100
     register: result
   - debug: var=result
   - name: saving iptables
     shell: service iptables save
     shell: systemctl enable firewalld
     shell: systemctl start firewalld
     shell: systemctl enable iptables
     shell: systemctl start iptables 
     register: result
   - debug: var=result
