--- #Playbook demo of debug and register statement
 - hosts: node1
   remote_user: ansible 
   become: yes
   become_method: sudo
   gather_facts: no
   tasks:
   - name: Installing telnet package
     yum:
      name: telnet
      state: latest
     register: result
   - debug: var=result
    
