--- #notificatin and handling the events
- hosts: node1
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Install nginx web server
    yum:   
     name: nginx
     state: latest
    notify:
    - enable and start the nginx service
  handlers: 
  - name: enable and start the nginx service
    service:
      name: nginx
      enabled: yes
      state: restarted

