--- #<<< Starting ---Cassandra--- installation >>>
 - hosts: web_servers 
   gather_facts: yes
   remote_user: ansible
   become: yes
   become_method: sudo
   vars:
    cluster_name: test_cluster
    seeds: 10.1.53.98,10.1.53.100
   tasks:
    - name: Copying Java Installation files 
      copy:
          src: jdk-8u171-linux-x64.rpm   
          dest: /tmp/jdk-8u171-linux-x64.rpm
    
    - name: Install Java JDK
      become: yes 
      yum:
        name: /tmp/jdk-8u171-linux-x64.rpm 
        state: present

    - name: Clean up -Java rpm files
      become: yes
      file:
       state: absent
       path: /tmp/jdk-8u171-linux-x64.rpm 
    
#    - name: Adding Cassandra.repo
#      become: true
#      copy: 
#        src: cassandra.repo
#        dest: /etc/yum.repos.d/cassandra.repo
#        owner: root
#        group: root
#        mode: 0644

    - name: Copy Cassandra Files
      copy:
         src: cassandra-2.2.12-1.noarch.rpm
         dest: /tmp/cassandra-2.2.12-1.noarch.rpm  


    - name: Installing Cassandra 
      become: true 
      yum:  
        name: /tmp/cassandra-2.2.12-1.noarch.rpm
        state: present

    - name: Clean up - rpm files
      become: yes
      file:
       state: absent
       path: /tmp/cassandra-2.2.12-1.noarch.rpm  
     
    - name: Start Cassandra
      become: true
      service:
         name: cassandra
         state: started
