--- #<<< Given IP based node - Java and Cassandra Standalone installation >>>
 - hosts: '{{my_ip}}'
   gather_facts: yes
   remote_user: '{{user}}' 
   become: yes
   become_method: sudo
   tasks:
    - name: Installing required packages
      yum:
        name:   
          - wget
          - iptables-services

    - name: Install Java Open-JDK and open-JDK-devel
      become: yes 
      yum:
        name: 
           - java-1.8.0-openjdk
           - java-1.8.0-openjdk-devel  
        state: latest
      
    - name: Downloading Cassandra RPM file
      get_url:
           url: http://www.apache.org/dist/cassandra/redhat/22x/cassandra-2.2.12-1.noarch.rpm
           dest: /tmp/cassandra-2.2.12-1.noarch.rpm
       

#    - name: Adding Cassandra.repo
#      become: true
#      copy: 
#        src: cassandra.repo
#        dest: /etc/yum.repos.d/cassandra.repo
#        owner: root
#        group: root
#        mode: 0644

#    - name: Copy Cassandra Files
#      copy:
#       src: cassandra-2.2.12-1.noarch.rpm
#       dest: /tmp/cassandra-2.2.12-1.noarch.rpm  


    - name: Installing Cassandra 
      become: true 
      yum:  
       name: /tmp/cassandra-2.2.12-1.noarch.rpm
       state: present

    - name: Clean up - rpm files
      become: yes
      file:
       state: absent
       path:
         -  /tmp/cassandra-2.2.12-1.noarch.rpm  

    - name: Configuring Centos Host system for cassandra
      selinux:
        policy=targeted
        state=disabled
      notify:
        - Start Cassandra
        - restarting server
#       - waiting for server to restart
        
   handlers:
#    - name: restart server
#      shell: sleep 2 && shutdown -r now "Ansible Updates triggered"
#      async: 1
#      poll: 0
#      ignore_errors: True 

#    - name: waiting for server to restart
#      local_action: wait_for
#            host= '{{my_ip}}'
#            port=22
#            state=started
#            delay=10
#            timeout=300
#     sudo: False
 
    - name: Start Cassandra
      become: true
      shell: service cassandra start

    - name: restarting server
      shell: sleep 2 && reboot
      async: 1
      poll: 0
      ignore_errors: True 
