--- #<<configuring firewall on all the given nodes>>>
- name: <<Enable 7000 and 9042 TCP ports for node <-> node communication>>
  hosts: all 
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:

   - name: Enable Firewalld
     service: 
       name: firewalld
       enabled: yes
     notify: 
         - Start Firewalld

   - name: open ports
     firewalld:
       port: "{{item}}"
       permanent: true
       state: enabled
     with_items:
       - 7000/tcp
       - 9042/tcp
     notify:
       - Reload Firewalld
 


 
