--- # Configuring Linux System - Selinux permissions 
- name: <<Configuring the Linux System>>
  hosts: all 
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:

   - name: Disable Selinux
     selinux: 
       policy=tergeted
       state=disabled
     notify: 
         - Restart Server
         - Wait for Server to Restart
         - Restart Firewalld

 


 
