---
- name: setting fact
  set_fact: namenodeipv4={{ hostvars[inventory_hostname]['ansible_default_ipv4']['addre
ss'] }}
  when: inventory_hostname in groups['namenode']

- name: Copy fact to other servers
  set_fact:
    name_node_ipv4: "{{ namenodeipv4 }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"-

