---
### Variables Listed here are applicable to all host groups ###

### Cassandra Cluster name (Upper Case only) ###
cluster_name: "{{ hostvars[inventory_hostname]['group_names'][0] }}"

### Cassandra Machine Owner ### (default - root)
cassandra_user: "{{ cass_user }}"

### Cassandra Machine Group ### (default - root)
cassandra_group: "{{ cass_group }}"

### Seed_ip(s) ### (Ip addresses of seeds as read from the hosts file)
seed_ip: "{{ groups['seed_nodes'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',')  }}"

### endpoint_snitch ### (set either, Case Sensitive***)

# SimpleSnitch for  single DC or GossipFileSnitch for Multiple DC 
endpoint_snitch: "SimpleSnitch"

### listen address: Gives the node an IP address to listen ###
listen_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
 
### rpc_address: Deals with the client communicatons to node ###

## Set to 0.0.0.0 to allow client communication, else set to node ip*** ##
#0.0.0.0 for cqlsh into current node direclty
rpc_address: 0.0.0.0      
 
##cqlsh <IP> <native_tarnsport_port_number> to cqlsh into node ## (9160 - default port)
#rpc_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"  

### Broadcast_rpc_address << If rpc_address is set to 0.0.0.0 set this to node ip*** ###
broadcast_rpc_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"    # node ip (default)


### auto_bootstrap >>> True or False ### (False - preferred)
auto_bootstrap: false 
