--- # handlers file for handling misc. fns from the tasks

- name: Enable_Firewalld
  become: yes
  service:
     name: firewalld
     enabled: yes
 
- name: Start_Firewalld 
  service:
    name: firewalld
    state: started
                   
- name: Stop_Firewalld
  service:
    name: firewalld
    status: stopped

- name: Restart_Firewalld
  service:
    name: firewalld
    status: restarted

- name: Reload_Firewalld
  become: yes
  shell: firewall-cmd --reload 

- name: Enable_iptables_service
  service:
    name: iptables
    enabled: yes

- name: Start_iptables_service
  service:
    name: iptables
    state: started

- name: Restart_iptables_service
  service:
    name: iptables
    state: restarted 

- name: Save_iptable_configuration 
  shell: service iptables save                      
 
- name: Restart_Server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: True
  
- name: Wait_for_Server_to_Restart
  local_action: wait_for
       host={{ inventory_hostname }}
       port=22
       state=started
       delay=10
       timeout=300
  sudo: False

- name: Stop_Cassandra_Service
  become: yes
  shell: systemctl stop cassandra  

- name: Enable_Firewalld
  become: yes
  service:
    name: firewalld
    enabled: yes  

- name: Restart_Cassandra_Service
  become: yes
  shell: systemctl restart cassandra
