--- #<< Main Playbook to Configure Cassandra Cluster in the Given Hosts>>

- name: Disable Selinux
  selinux:
     policy=targeted
     state=disabled
  notify:
      - Restart_Server
      - Wait_for_Server_to_Restart
      - Restart_Firewalld

- name: <<start Firewall>>
  shell: systemctl restart firewalld 

- name: Adding Port(s) 7000 and 9042 to firewall rules
  firewalld:
     port: "{{item}}"
     permanent: true
     state: enabled
  with_items:
     - 7000/tcp
     - 9042/tcp
  notify:
     - Reload_Firewalld
     - Restart_Firewalld

- name: Installing iptables service
  yum:
    name:
      - iptables-services
    state: latest
  notify:
       - Enable_iptables_service
       - Start_iptables_service

- name: IPtable configuration - <7000> listen port
  iptables:
     action: append
     chain: INPUT
     comment: "Cassandra_listen_port"
     ctstate: NEW,ESTABLISHED
     protocol: tcp
     match: tcp
     destination_port: 7000
     jump: ACCEPT
     source: '{{ item }}'
  when: item != inventory_hostname
  with_items:
           - "{{ groups['all'] }}"
  notify:
     - Save_iptable_configuration

- name: IPtable configuration - <9042> native transport port
  iptables:
     action: append
     chain: INPUT
     comment: "Cassandra_Native_Transport_port"
     ctstate: NEW,ESTABLISHED
     protocol: tcp
     match: tcp
     destination_port: 9042
     jump: ACCEPT
     source: '{{ item }}'
  when: item != inventory_hostname
  with_items:
           - "{{ groups['all'] }}"
  notify:
     - Save_iptable_configuration

#- name: Configuring Cassandra - Conf. Template and Permissions
#- name: <<Configuring Cassandra>>
- name: Ensure Cassandra is not running
  shell: clear
  notify:
      - Stop_Cassandra_Service

- name: Clearing preconfigured cassandra properties << Old DATA & Commitlogs!!! >>
  become: yes
  shell: nodetool decommission
  shell: rm -rf /var/log/cassandra/*
  shell: rm -rf /var/lib/cassandra/data/system/*  
  shell: rm -rf /var/lib/cassandra/commitlog/*  

- name: Updating Cassandra Configuration
  template:
      src: cassandra.yaml.j2 
      dest: /etc/cassandra/conf/cassandra.yaml
      owner: "{{cassandra_user}}"
      group: "{{cassandra_group}}"
      mode: 0644
  notify:
       - Restart_Cassandra_Service
      

