--- #<< Main Playbook to Configure Cassandra Cluster in the Given Hosts>>
#- name: Stop Firewall to Configure Linux-Selinux
#  service: firewalld
#  state: stopped
#  notify:
#      - Stop Firewalld

- name: Disable Selinux
  selinux:
     policy=targeted
     state=disabled
  notify:
      - Restart Server
      - Wait for Server to Restart
      - Restart Firewalld

#- name: <<Enable 7000 and 9042 TCP ports for node <-> node communication>>

- name: Ensure Firewalld is enabled
  shell:  systemctl status firewalld
  notify:
      - Enable firewalld

#- name: adding ip(s) with 7000 and 9042 to iptable

- name: Adding Port(s) 7000 and 9042 to firewall rules
  firewalld:
     port: "{{item}}"
     permanent: true
     state: enabled
  with_items:
     - 7000/tcp
     - 9042/tcp
  notify:
     - Reload Firewalld
     - Restart Firewalld

- name: Installing iptables service
  yum:
    name:
      - iptables-services
    state: latest
  notify:
       - Enable iptables service
       - Start iptables service

- name: IPtable configuration
  become: yes
  shell: iptables -A INPUT -p tcp -s '{{item}}' -m multiport --dports 7000 -m state --state NEW,ESTABLISHED -j ACCEPT
  shell: iptables -A INPUT -p tcp -s '{{item}}' -m multiport --dports 9042 -m state --state NEW,ESTABLISHED -j ACCEPT
  with_items:
     - "{{ hostvars[ '{{groups['all']}}' ]['ansible_eth0']['ipv4']['address'] }}"
  notify:
     - Saving iptables service
     - Restart iptables service 

#- name: Configuring Cassandra - Conf. Template and Permissions
#- name: <<Configuring Cassandra>>
- name: Ensure Cassandra is not running
  shell: service cassandra start
  notify:
      - Stop Cassandra Service

- name: Updating Cassandra Configuration
  template:
      src: "{{item}}.j2"
      dest: /etc/cassandra/conf/"{{item}}"
      owner: "{{cassandra_user}}"
      group: "{{cassandra_group}}"
      mode: 0644
  with_items:
        - "cassandra.yaml"
  notify:
       - Restart Cassandra Service
      

