--- # Configuring Cassandra - Conf. Template and Permissions
- name: <<Configuring Cassandra>>
  hosts: all 
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
   - name: Ensure Cassandra is not running
     notify: 
       - Stop Cassandra Service

   - name: Updating Cassandra Configuration
     template:
         src: "{{item}}.j2"
         dest: /etc/cassandra/conf/{{item}}
         owner: "{{cassandra_user}}"
         group: "{{cassandra_group}}"
         mode: 0644
      with_items:
          - "cassandra.yaml"
      notify: 
          - Restart Cassandra Service


      






 


 
