--- #<<configuring firewall on all the given nodes>>>
- name: <<Enable 7000 and 9042 TCP ports for node <-> node communication>>
  hosts: all 
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:

   - name: Ensure Firewalld is enabled
     notify: 
         - Enable Firewalld

   - name: Adding Port(s) 7000 and 9042 to firewall rules 
     firewalld:
       port: "{{item}}"
       permanent: true
       state: enabled
     with_items:
       - 7000/tcp
       - 9042/tcp
     notify:
       - Reload Firewalld
       - Restart Firewalld

 
