--- #<<configuring firewall>>
- hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
   - name: Enable Firewalld
     service: 
       name: firewalld
       enabled: yes
   - name: start Firewalld
     service: 
       name: firewalld
       state: started


 
