--- #Installing Cassandra
- name: Copy Cassandra repo file
  copy: 
    src: cassandra.repo
    dest: /etc/yum.repos.d/cassandra.repo
    owner: root
    group: root
    mode: 0644

- name: Install Cassandra Packages
  yum: name=cassandra state=installed
  become: true

- name: Override cassandra.yaml file
  template: 
    src: cassandra.yaml 
    dest: /etc/cassandra/conf/
      
- name: Run Cassandra 
  service:
    name: cassandra
    state: started
    
