--- #This is a structural YAML examoke to install httpd on centos
- hosts: node1  
  remote_user : ansible 
  become: yes 
  become_method: sudo 
  connection: ssh 
  gather_facts: Yes 
  vars: 
    username: myuser
  tasks:
  - name: Install HTTPDserver on the Centos Node1
    yum:
      name: httpd
      state: latest
    notify:
    - startservice
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted
