--- #Installing Cassandra
- name: Copy Cassandra repo file
  copy: 
    src: cassandra.repo
    dest: /etc/yum.repos.d/cassandra.repo
    owner: root
    group: root
    mode: 0644

#name: Creating Cassandra group as system group and member of users group
 #become: yes
  #shell: groupadd -r cassandra
  #shell: useradd -r -m cassandra -g cassandra -G users
  #register: Completed!

- name: Install Cassandra Packages
  remote_user: root
  become: yes 
  yum: name=cassandra state=installed

#name: creating data and commitlog directories
  #remote_user: cassandra
  #become: yes
  #shell: sudo -u cassandra /usr/sbin/cassandra -f
  #shell: mkdir /var/lib/cassandra/commitlog
  #shell: mkdir /var/lib/cassandra/data
  #shell: chown -R  cassandra:cassandra /var/lib/cassandra/data
  #shell: chown -R  cassandra:cassandra /var/lib/cassandra/commitlog  
  

- name: Override cassandra.yaml file
  template: 
    src: cassandra.yaml 
    dest: /etc/cassandra/conf/cassandra.yaml
    owner: root
    group: root
    mode: 0644

- name: Starting cassandra
  remote_user: dataops
  become: yes
  command: ./cassandra -R 
  args:
    chdir: /opt/apache-cassandra-3.11.2/bin/
  

#- name: Run Cassandra from bin folder
#  command: ./cassandra -fR
#  args:
#    chdir: /home/dataops/apache-cassandra-3.0.x/bin/

#- name: Set up Cassandra HOME and add it to the execution path
#  become: yes  
#  shell: export CASSANDRA_HOME= /usr/share/cassandra
#  shell: export PATH=$PATH:$CASSANDRA_HOME/bin

#- name: Run Cassandra 
#  service:
#    name: cassandra
#    state: started

#- name: Changing the vm.max_map_count
#  become: yes
#  command: sysctl -w vm.max_map_count=1048575

#- name: creating data and commitlog directories
 # remote_user: root
 # shell: sudo -u cassandra /usr/sbin/cassandra -f
 # shell: mkdir /var/lib/cassandra/commitlog
 # shell: mkdir /var/lib/cassandra/data
 # shell: chown -R  cassandra:cassandra /var/lib/cassandra/data
 # shell: chown -R  cassandra:cassandra /var/lib/cassandra/commitlog

- name: Restart Cassandra
  service:
    name: cassandra
    state: restarted

